--- #YAML:1.0
name:               App-Pod2Epub
version:            0.02
abstract:           Convert Pod to an ePub eBook.
author:
    - John McNamara (jmcnamara@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::UUID:    0
    EBook::EPUB:   0.5
    File::Temp:    0
    Getopt::Long:  0
    Pod::Simple:   0
    Pod::Usage:    0
resources:
    repository:  http://github.com/jmcnamara/app-pod2epub
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
